version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - chroma_data:/app/src/chroma_storage
    depends_on:
      - db
    networks:
      - klugbot-network

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - klugbot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U klugbot -d klugbot_kb"]
      interval: 5s
      timeout: 5s
      retries: 5


networks:
  klugbot-network:
    driver: bridge

volumes:
  postgres_data:
  chroma_data: